[package]
name = "threads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
ansi-escapes = "0.1.1"

chrono = "0.4"
datetime = "0.5.2"


